config/routes.rb
ProjectX::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  resources :users
  resources :sessions
  resources :posts

  get 'resources/search' => 'resources#search'
  get 'resources/lan_detect' => 'resources#lan_detect'

  root :to => 'posts#new'

end

app/views/shared/_footer.html.erb
<div class="home-footer">
  <div class="home-container">
    <div class="clearfix">
      <div class="pull-right">
        <%= link_to t('footer.blog'), '#'%>
        <%= link_to t('footer.help'), '#'%>
        <%= link_to t('footer.contact'), '#'%>
        <%= link_to t('footer.twitter'), '#'%>
        <%= link_to t('footer.feedback'), '#'%>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="home-header">
  <div class="home-container">
    <%= link_to 'Writings', root_path, :class=>'logo'%>
    <nav>
      <ul>
        <li>
          <%= link_to t('admin.login'), new_session_path%>
        </li>
        <li>
          <%= link_to t('admin.signup'), new_user_path%>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/shared/_site_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SAMPLE EDITOR</a>
    </div>
    <div class="pull-right collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Help</a></li>
        <li><a href="#about">About Us</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/shared/_site_javascripts.html.erb
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "site_3rd_base" %>
<%= javascript_include_tag "site_base" %>

app/views/shared/_site_stylesheets.html.erb
<%= stylesheet_link_tag "site_3rd_base", media: 'all' %>
<%= stylesheet_link_tag "site_base", media: 'all'  %>
<%= stylesheet_link_tag "application", media: 'all'  %>